% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{float}
\usepackage{caption}
\captionsetup[table]{skip=4pt}
\captionsetup[figure]{skip=4pt}
\setlength{\parskip}{0pt}
\setlength{\intextsep}{6pt}
\usepackage{pdflscape}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\rfoot{\thepage}
\setlength{\headheight}{14pt}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Multi-Stage Area Probability Sample Design for the Detroit Transportation Security Survey},
  pdfauthor={Team Neyman; Namit Shrivastava; Nicholas Reign Lugu},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Multi-Stage Area Probability Sample Design for the Detroit
Transportation Security Survey}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{SURV 745 - PracTools Project Contact: namit507@gmail.com}
\author{Team Neyman \and Namit Shrivastava \and Nicholas Reign Lugu}
\date{April 11, 2026}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}

\setstretch{1}
\newpage

\section{Introduction}\label{introduction}

In this report, we present the sample design for a face-to-face survey
of residents of the City of Detroit, Michigan. We focus on
transportation security and transportation use. The key variables
include the proportion of residents living in a vehicle-free household,
the proportion whose main means of transportation is public transit, the
proportion who skip going somewhere due to transportation problems, and
the proportion who asked friends, family, or neighbors for
transportation help in the past month.

We use a multi-stage area probability sample in which census tracts
serve as primary sampling units (PSUs), block groups (BGs) serve as
secondary sampling units (SSUs), and persons are selected from area
listings within sampled BGs at the final stage. The design meets a
target of 1,000 responding adults, allocated equally across four age
groups, while accounting for differential expected response rates. We
also use the University of Michigan report Transportation Insecurity in
the Motor City as background context for why Detroit transportation
barriers are a meaningful substantive focus. The remainder of this
report describes how we built the frame, selected the sample, assessed
anticipated precision, and planned weighting and variance estimation.

\section{Sample Design}\label{sample-design}

\subsection{Goals of the Sample
Design}\label{goals-of-the-sample-design}

The goals of the sample design are to: (1) select a probability sample
yielding approximately 1,000 responding adults from the City of Detroit,
with 250 respondents in each of four age groups (18-34, 35-49, 50-64,
and 65+); (2) select 40 census tracts and, within each selected tract, 1
block group; (3) maintain a self-weighting design within each age group
so that every person in a given age domain has the same overall
probability of selection; and (4) achieve approximately equal field
workload across selected tracts by using probabilities proportional to a
composite measure of size reflecting the required age-specific sampling
rates.

\begin{table}[!h]
\centering
\caption{\label{tab:target-table}Target Completed Interviews and Expected Response Rates}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lrr}
\toprule
Age Group & Target Respondents & Expected Response Rate\\
\midrule
18-34 & 250 & 0.35\\
35-49 & 250 & 0.45\\
50-64 & 250 & 0.50\\
65+ & 250 & 0.65\\
\bottomrule
\end{tabular}}
\end{table}

\subsection{Target Population}\label{target-population}

The target population consists of all civilian, non-institutionalized
persons aged 18 years and older residing in the City of Detroit,
Michigan. Persons living in institutional settings are excluded because
the survey is designed as a household-based face-to-face survey.

\subsection{Area Sampling Frame: Units, Data Available, and Source of
the
Data}\label{area-sampling-frame-units-data-available-and-source-of-the-data}

\subsubsection{Data Sources}\label{data-sources}

We constructed the area sampling frame from two sources: (1) a file of
Detroit census tract FIPS codes obtained from the City of Detroit Open
Data Portal; and (2) a Detroit census data file containing tract-level
and block-group-level counts from the 2020 Decennial Census Demographic
and Housing Characteristics (DHC) Summary File, including total
households, total persons, and age-by-sex counts from table P12. We
relied on the Census API documentation at
https://api.census.gov/data.html and the Census API key request page at
https://api.census.gov/data/key\_signup.html when describing the
reproducible data-access path. We also followed the Census geography
glossary and reference-map guidance when describing census tracts, block
groups, and map interpretation.

\subsubsection{Frame Construction}\label{frame-construction}

We deduplicated the initial tract file at the tract level because some
special geographic units appeared more than once in the source file. We
then removed tracts with zero adult population and tracts with fewer
than 50 adults from the operational frame because those units would not
function as meaningful household survey PSUs and would create unstable
sampling rates and unnecessary field burden. We retained tracts with
only one block group, and in those cases that single block group is
selected with certainty at stage 2.

\begin{table}[!h]
\centering
\caption{\label{tab:frame-cleaning-summary}Summary of Frame Construction}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lr}
\toprule
Step & Count\\
\midrule
Initial tract records after deduplication & 276\\
Tracts with zero adults aged 18+ & 6\\
Tracts with 1-49 adults aged 18+ & 4\\
Total tracts removed & 10\\
Final tract frame & 266\\
Final block group frame & 614\\
\bottomrule
\end{tabular}}
\end{table}

\subsection{Assigning Measures of Size to
Units}\label{assigning-measures-of-size-to-units}

A central requirement of the design is to achieve 250 completed
interviews in each age group despite differing expected response rates.
For age group \(g\), the required person-level sampling fraction is:

\[
f_g = \frac{n_g}{r_g N_g}
\]

where \(n_g\) is the target number of completed interviews, \(r_g\) is
the expected response rate, and \(N_g\) is the Detroit population total
in age group \(g\).

To support both the age-group targets and approximately equal field
workload, the design uses the following composite measure of size (MOS)
for each unit \(i\):

\[
MOS_i = \sum_{g=1}^{4} f_g\, N_{g,i}
\]

where \(N_{g,i}\) is the count of persons in age group \(g\) in unit
\(i\). This MOS reflects the expected pre-response workload implied by
the differential sampling fractions required by each age domain.

\begin{table}[!h]
\centering
\caption{\label{tab:mos-construction}Age-Specific Sampling Fractions Used in the Composite MOS}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lrrrr}
\toprule
Age Group & Population Total & Target Respondents & Expected Response Rate & Required Sampling Fraction\\
\midrule
18-34 & 161344 & 250 & 0.35 & 0.004427\\
35-49 & 113270 & 250 & 0.45 & 0.004905\\
50-64 & 117755 & 250 & 0.50 & 0.004246\\
65+ & 87733 & 250 & 0.65 & 0.004384\\
\bottomrule
\end{tabular}}
\end{table}

The total composite MOS is 2,154.46. With 40 tracts selected, the design
implies an expected pre-response workload of 53.86 listed adults per
selected tract, versus an expected 25.0 completed interviews per tract.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{REPORT_NEYMANN_files/figure-pdf/fig-mos-distribution-1.pdf}}

}

\caption{\label{fig-mos-distribution}Distribution of the Composite MOS
Across Detroit Census Tracts. The skewed distribution confirms that
equal-probability selection would produce unequal workloads; PPS
selection equalizes workload by giving larger tracts higher inclusion
probabilities.}

\end{figure}%

\begin{table}[!h]
\centering
\caption{\label{tab:frame-descriptive-stats}Descriptive Statistics for the Detroit Tract Frame (N = 266 tracts)}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lrrrrr}
\toprule
Variable & Mean & Median & SD & Min & Max\\
\midrule
Total Persons & 2402.6 & 2247.5 & 1045.9 & 83.0 & 5518.0\\
Total Households & 1165.0 & 1123.0 & 473.0 & 39.0 & 3906.0\\
Adults 18+ & 1804.9 & 1736.5 & 767.3 & 71.0 & 4417.0\\
Age 18-34 & 606.6 & 571.0 & 333.3 & 20.0 & 3241.0\\
Age 35-49 & 425.8 & 400.5 & 191.1 & 17.0 & 1084.0\\
Age 50-64 & 442.7 & 422.0 & 184.5 & 16.0 & 1168.0\\
Age 65+ & 329.8 & 291.0 & 194.4 & 6.0 & 1623.0\\
Composite MOS & 8.1 & 7.8 & 3.4 & 0.3 & 19.5\\
\bottomrule
\end{tabular}}
\end{table}

\begin{table}[!h]
\centering
\caption{\label{tab:frame-descriptive-stats}Distribution of the Number of Block Groups per Tract}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{rr}
\toprule
Block Groups per Tract & Number of Tracts\\
\midrule
1 & 40\\
2 & 134\\
3 & 68\\
4 & 19\\
5 & 4\\
6 & 1\\
\bottomrule
\end{tabular}}
\end{table}

The frame contains 266 operational tracts and 614 operational block
groups. The tract-level composite MOS varies substantially across the
city, supporting the use of PPS selection to spread the sample
efficiently while preserving target age-group yields.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{REPORT_NEYMANN_files/figure-pdf/fig-age-composition-1.pdf}}

}

\caption{\label{fig-age-composition}Age Distribution: Population Share
vs.~Equal Sample Allocation. Blue bars show each age group's share of
the Detroit adult population; orange bars show the equal 25\% allocation
in the sample. The 18--34 group is overrepresented in the population
relative to its sample share, while the 65+ group is underrepresented,
motivating the use of domain-specific sampling fractions.}

\end{figure}%

\subsection{Could a Single Sampling Rate Meet the Age-Group
Targets?}\label{could-a-single-sampling-rate-meet-the-age-group-targets}

A useful alternative is a design applying the same person-level sampling
rate \(f\) to all adults. Under this design, \(f\) satisfies:

\[
f = \frac{1000}{\displaystyle\sum_g N_g\, r_g}.
\]

\begin{table}[!h]
\centering
\caption{\label{tab:equal-rate-analysis}Expected Respondents Under a Design with the Same Sampling Rate for All Persons}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lrrrrr}
\toprule
Age Group & Population & Exp. Response Rate & Target & Exp. Respondents & Difference\\
\midrule
18-34 & 161344 & 0.35 & 250 & 252.8 & 2.8\\
35-49 & 113270 & 0.45 & 250 & 228.2 & -21.8\\
50-64 & 117755 & 0.50 & 250 & 263.6 & 13.6\\
65+ & 87733 & 0.65 & 250 & 255.3 & 5.3\\
\bottomrule
\end{tabular}}
\end{table}

An equal-rate design would require a sampling rate of 0.004477. We
considered that design because it is simpler and would produce a fully
self-weighting sample for all adults. We rejected it because it cannot
meet the age-domain targets exactly. As the table and figure below show,
the 35-49 group would fall materially short of 250, while the 50-64 and
65+ groups would overshoot. Because the four domain-specific targets are
fixed requirements, we do not view the equal-rate design as appropriate.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{REPORT_NEYMANN_files/figure-pdf/fig-equal-vs-domain-1.pdf}}

}

\caption{\label{fig-equal-vs-domain}Expected Respondents Under
Equal-Rate vs.~Domain-Specific Sampling. The dashed line marks the
250-respondent target for each age group. The equal-rate design misses
the target for the 35--49 group and overshoots for 50--64 and 65+; the
domain-specific design hits 250 exactly in all groups.}

\end{figure}%

\section{Sample Selection}\label{sample-selection}

\subsection{Method of Selection}\label{method-of-selection}

The sample is selected in three stages:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Stage 1 (PSUs):} Select 40 census tracts from the tract frame
  using systematic PPS sampling with the composite MOS, with the frame
  sorted in ascending FIPS-code order.
\item
  \textbf{Stage 2 (SSUs):} Within each selected tract, select exactly 1
  block group using PPS sampling with the block-group-level composite
  MOS. For tracts containing only one block group, that block group is
  selected with certainty.
\item
  \textbf{Stage 3 (persons):} Within each sampled block group, list all
  occupied housing units and all adults aged 18+. Within each age
  domain, select persons at the domain-specific rate \(f_{g,ij}\)
  required to yield the expected completed interviews.
\end{enumerate}

\subsection{Selected Units and Their
Characteristics}\label{selected-units-and-their-characteristics}

\begin{table}[!h]
\centering
\caption{\label{tab:selected-psus-table}Selected PSUs (Census Tracts) and Their Characteristics}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{llrrrrr}
\toprule
Tract FIPS & Name & Total Pop & Adults 18+ & Composite MOS & Inclusion Prob. & No. BGs\\
\midrule
26163500200 & Census Tract 5002 & 3037 & 2088 & 9.41 & 0.1746 & 2\\
26163500900 & Census Tract 5009 & 3706 & 2573 & 11.58 & 0.2151 & 2\\
26163501400 & Census Tract 5014 & 3624 & 2685 & 12.07 & 0.2241 & 3\\
26163502000 & Census Tract 5020 & 1858 & 1289 & 5.81 & 0.1078 & 1\\
26163503400 & Census Tract 5034 & 886 & 673 & 3.03 & 0.0562 & 1\\
26163505100 & Census Tract 5051 & 2888 & 2253 & 10.08 & 0.1871 & 3\\
26163506100 & Census Tract 5061 & 1875 & 1379 & 6.19 & 0.1149 & 1\\
26163506900 & Census Tract 5069 & 3579 & 2551 & 11.47 & 0.2130 & 3\\
26163508000 & Census Tract 5080 & 1098 & 835 & 3.74 & 0.0695 & 2\\
26163511400 & Census Tract 5114 & 2005 & 1675 & 7.48 & 0.1388 & 3\\
26163513900 & Census Tract 5139 & 1556 & 1165 & 5.20 & 0.0966 & 2\\
26163515700 & Census Tract 5157 & 4618 & 4417 & 19.55 & 0.3630 & 3\\
26163516700 & Census Tract 5167 & 3218 & 2604 & 11.61 & 0.2155 & 3\\
26163517500 & Census Tract 5175 & 2856 & 2528 & 11.21 & 0.2080 & 2\\
26163520300 & Census Tract 5203 & 2622 & 2505 & 11.19 & 0.2078 & 3\\
26163521800 & Census Tract 5218 & 1466 & 1179 & 5.25 & 0.0976 & 1\\
26163523300 & Census Tract 5233 & 2914 & 2023 & 9.15 & 0.1699 & 3\\
26163524200 & Census Tract 5242 & 4366 & 2884 & 13.08 & 0.2429 & 3\\
26163525700 & Census Tract 5257 & 4403 & 2906 & 13.20 & 0.2451 & 4\\
26163526400 & Census Tract 5264 & 1417 & 964 & 4.35 & 0.0808 & 2\\
26163530800 & Census Tract 5308 & 1394 & 1092 & 4.88 & 0.0906 & 2\\
26163531800 & Census Tract 5318 & 1500 & 1127 & 5.04 & 0.0937 & 2\\
26163533600 & Census Tract 5336 & 1390 & 1035 & 4.66 & 0.0864 & 2\\
26163534700 & Census Tract 5347 & 3056 & 2214 & 9.92 & 0.1843 & 3\\
26163535600 & Census Tract 5356 & 3727 & 2896 & 12.95 & 0.2404 & 4\\
26163536500 & Census Tract 5365 & 2097 & 1597 & 7.18 & 0.1332 & 2\\
26163537200 & Census Tract 5372 & 583 & 450 & 2.03 & 0.0377 & 1\\
26163538200 & Census Tract 5382 & 1972 & 1624 & 7.26 & 0.1349 & 2\\
26163538600 & Census Tract 5386 & 4758 & 3619 & 16.21 & 0.3010 & 4\\
26163539200 & Census Tract 5392 & 4863 & 3908 & 17.48 & 0.3245 & 3\\
26163539600 & Census Tract 5396 & 3197 & 2439 & 10.93 & 0.2030 & 2\\
26163540400 & Census Tract 5404 & 2632 & 2026 & 9.07 & 0.1684 & 2\\
26163540900 & Census Tract 5409 & 3420 & 2641 & 11.83 & 0.2197 & 3\\
26163541500 & Census Tract 5415 & 3625 & 2897 & 12.95 & 0.2405 & 2\\
26163542300 & Census Tract 5423 & 2255 & 1740 & 7.82 & 0.1452 & 2\\
26163543100 & Census Tract 5431 & 2455 & 1915 & 8.57 & 0.1591 & 2\\
26163544000 & Census Tract 5440 & 2534 & 1985 & 8.90 & 0.1652 & 1\\
26163545500 & Census Tract 5455 & 3878 & 2590 & 11.69 & 0.2171 & 3\\
26163545900 & Census Tract 5459 & 3758 & 2530 & 11.41 & 0.2118 & 2\\
26163546700 & Census Tract 5467 & 2816 & 2091 & 9.38 & 0.1741 & 2\\
\bottomrule
\end{tabular}}
\end{table}

\subsection{Selection Probabilities at Each
Stage}\label{selection-probabilities-at-each-stage}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{REPORT_NEYMANN_files/figure-pdf/fig-pi-vs-mos-1.pdf}}

}

\caption{\label{fig-pi-vs-mos}Tract Inclusion Probabilities
vs.~Composite Measure of Size. The near-perfect linear relationship
confirms that systematic PPS selection correctly assigns each tract an
inclusion probability proportional to its composite MOS.}

\end{figure}%

For tract \(i\), the first-stage inclusion probability is computed using
the inclusionprobabilities() function from the R sampling package, which
rescales the raw PPS probabilities to sum to exactly \(n_I = 40\) while
correctly assigning probability 1 to any tract whose raw probability
exceeds 1 (certainty units):

\[
\pi_{1i} = \text{inclusionprobabilities}(MOS_i,\; 40), \quad \sum_i \pi_{1i} = 40.
\]

For block group \(j\) within selected tract \(i\), the conditional
second-stage probability is:

\[
\pi_{2j|i} = \frac{MOS_{ij}}{\sum_{\ell \in i} MOS_{i\ell}},
\]

and the overall block-group probability is \[
\pi_{ij}^{BG} = \pi_{1i}\,\pi_{2j|i}
\].

For a person in age group \(g\) in selected block group \(j\), the
within-BG sampling rate is \(f_{g,ij} = f_g / \pi_{ij}^{BG}\), so the
overall person probability is:

\[
\pi_{g,ij} = \pi_{ij}^{BG} \cdot f_{g,ij} = f_g,
\]

confirming that the design is self-weighting within each age group.

\begin{table}[!h]
\centering
\caption{\label{tab:sample-probability-summary}Summary of Selection Probabilities and Workload}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lr}
\toprule
Metric & Value\\
\midrule
Number of selected tracts & 40.0000\\
Number of selected block groups & 40.0000\\
Mean tract inclusion probability & 0.1740\\
Minimum tract inclusion probability & 0.0377\\
Maximum tract inclusion probability & 0.3630\\
Mean block-group overall inclusion probability & 0.0803\\
Expected persons approached per sampled tract & 53.8614\\
Expected completed interviews per sampled tract & 25.1819\\
Operational persons selected per sampled tract & 53.8750\\
Operational expected completed interviews per sampled tract & 25.0087\\
\bottomrule
\end{tabular}}
\end{table}

\subsection{How Persons Should Be Selected from Area
Listings}\label{how-persons-should-be-selected-from-area-listings}

For each sampled block group, interviewers should first prepare a
complete listing of all occupied housing units and all adults aged 18+
within them, classifying each adult into one of the four age domains.
Separate within-BG lists are then formed for each domain.

Within each domain, persons should be selected using the integer counts
shown in the sample file. We derive those counts by a largest-remainder
(Hamilton method) allocation: each BG's share of the domain total
workload (\texttt{listed\_g}) is first expressed as a proportional share
of the domain target (for example, 714 for age 18-34), then floored to
integers, with any remaining units assigned to BGs with the largest
fractional parts. This ensures the integer counts sum exactly to the
domain target and are distributed proportionally to the BG-level
workload. In practice, we would ask interviewers to create a complete
list of occupied housing units, roster every adult age 18 or older,
classify each adult into one of the four age groups, and then select the
required number within each age group by systematic sampling with a
random start or by a reproducible random-number sort. That procedure
gives every listed adult in the domain a known probability of selection.

\begin{table}[!h]
\centering
\caption{\label{tab:expected-by-domain}Persons Selected and Expected Completed Interviews by Age Group}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lrr}
\toprule
Age Group & Persons Selected & Expected Completed Interviews\\
\midrule
18-34 & 714 & 249.9\\
35-49 & 556 & 250.2\\
50-64 & 500 & 250.0\\
65+ & 385 & 250.2\\
Total & 2155 & 1000.4\\
\bottomrule
\end{tabular}}
\end{table}

\section{Anticipated Precision}\label{anticipated-precision}

The key precision requirement concerns the estimated proportion of
Detroit adults whose main means of transportation is public transit.
Under a complex sample design:

\[
Var(\hat{p}) = DEFF \times \frac{p(1-p)}{n},
\]

where \(n = 1{,}000\) and \(DEFF\) is the design effect. Because the
design has one sampled BG per tract, within-cluster homogeneity still
creates a design effect greater than 1. The table below reports
anticipated precision across plausible design effects (1.2 to 1.8) and
several assumed proportions.

\begin{table}[!h]
\centering
\caption{\label{tab:precision-table}Anticipated Precision for Estimated Proportions Under Plausible Design Effects}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{9}{11}\selectfont
\begin{tabular}[t]{rrrrl}
\toprule
Assumed Proportion & DEFF & Standard Error & Margin of Error & 95\% CI\\
\midrule
0 & 1.2 & 0 & 0.0204 & {}[0.080, 0.120]\\
0 & 1.5 & 0 & 0.0228 & {}[0.077, 0.123]\\
0 & 1.8 & 0 & 0.0249 & {}[0.075, 0.125]\\
0 & 1.2 & 0 & 0.0242 & {}[0.126, 0.174]\\
0 & 1.5 & 0 & 0.0271 & {}[0.123, 0.177]\\
0 & 1.8 & 0 & 0.0297 & {}[0.120, 0.180]\\
0 & 1.2 & 0 & 0.0272 & {}[0.173, 0.227]\\
0 & 1.5 & 0 & 0.0304 & {}[0.170, 0.230]\\
0 & 1.8 & 0 & 0.0333 & {}[0.167, 0.233]\\
0 & 1.2 & 0 & 0.0294 & {}[0.221, 0.279]\\
0 & 1.5 & 0 & 0.0329 & {}[0.217, 0.283]\\
0 & 1.8 & 0 & 0.0360 & {}[0.214, 0.286]\\
0 & 1.2 & 0 & 0.0311 & {}[0.269, 0.331]\\
0 & 1.5 & 0 & 0.0348 & {}[0.265, 0.335]\\
0 & 1.8 & 0 & 0.0381 & {}[0.262, 0.338]\\
\bottomrule
\end{tabular}}
\end{table}

If the true public-transit proportion is around 0.15, the margin of
error ranges from approximately ±0.024 (DEFF = 1.2) to ±0.030 (DEFF =
1.8), indicating adequate citywide precision. The equal domain
allocation also supports reliable age-subgroup estimates.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{REPORT_NEYMANN_files/figure-pdf/fig-precision-curves-1.pdf}}

}

\caption{\label{fig-precision-curves}Anticipated Standard Error of an
Estimated Proportion by True Proportion and Design Effect (n = 1,000).
Dashed vertical line marks p = 0.15, the assumed public-transit
proportion. The shaded band spans DEFF = 1.2 to 1.8.}

\end{figure}%

\section{Description of Weighting
Plan}\label{description-of-weighting-plan}

Because the design is self-weighting within each age group, the base
weight for a respondent in age group \(g\) is constant within that
group:

\[
w_{\text{base},g} = \frac{1}{f_g}.
\]

\begin{table}[!h]
\centering
\caption{\label{tab:weighting-table}Base Weights by Age Group}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lrr}
\toprule
Age Group & Sampling Fraction & Base Weight\\
\midrule
18-34 & 0.004427 & 225.9\\
35-49 & 0.004905 & 203.9\\
50-64 & 0.004246 & 235.5\\
65+ & 0.004384 & 228.1\\
\bottomrule
\end{tabular}}
\end{table}

After data collection, we would apply a nonresponse adjustment within
weighting cells defined by age group and, where feasible, geographic
weighting classes such as groups of sampled tracts with similar response
propensities. After that nonresponse adjustment, we would calibrate the
weights to known external population controls, at minimum the
age-group-by-sex totals from the 2020 Census. If additional reliable
controls are available, such as race and ethnicity margins, we would use
raking across multiple marginal distributions to reduce nonresponse bias
and improve precision.

\section{Variance Estimation}\label{variance-estimation}

For design-based variance estimation, we recommend defining the selected
census tracts as PSUs. Because no explicit stratification is built into
the present design, a conservative approach is to treat the entire
sample as a single stratum with 40 PSUs. A modestly improved approach is
to form variance-estimation strata by pairing adjacent sampled tracts in
the sorted PPS frame order, thereby capturing some implicit geographic
stratification; this yields 20 strata with 2 PSUs each.

The final analysis data file should contain at minimum: (1) a final
respondent weight, (2) a PSU identifier corresponding to the sampled
tract FIPS code, and (3) a variance stratum variable. Analysts can then
compute Taylor-series linearized standard errors or
replicate-weight-based variances using standard survey software such as
the \texttt{survey} package in R, Stata's \texttt{svy} suite, or SAS
\texttt{PROC\ SURVEYMEANS}. Because there is only one sampled block
group per tract, the tract remains the PSU for all analyses; treating
block groups as PSUs would incorrectly inflate degrees of freedom.

\section{Maps}\label{maps}

\subsection{The City of Detroit}\label{the-city-of-detroit}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{REPORT_NEYMANN_files/figure-pdf/detroit-map-1.pdf}}

}

\caption{Census Tracts in the Detroit Operational Frame. All 266 tracts
meeting the minimum population threshold are shown; the 40 selected PSUs
are highlighted in blue.}

\end{figure}%

\subsection{Selected Tracts and Block
Groups}\label{selected-tracts-and-block-groups}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{REPORT_NEYMANN_files/figure-pdf/selected-map-1.pdf}}

}

\caption{Selected Sample: PSU Tracts (blue circles) and SSU Block Groups
(red circles). Circle size is proportional to the composite MOS,
illustrating that larger tracts are selected with higher probability
under PPS. Each selected tract contains exactly one selected block group
(red dot).}

\end{figure}%

\newpage

\section{Appendix}\label{appendix}

\subsection{Codebook of Frame and Sample
Files}\label{codebook-of-frame-and-sample-files}

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{ll}
\caption{\label{tab:codebook-tables}Codebook for the Tract Frame File (FRAME1\_NEYMAN.csv)}\\
\toprule
Variable Name & Description\\
\midrule
\endfirsthead
\caption[]{Codebook for the Tract Frame File (FRAME1\_NEYMAN.csv) \textit{(continued)}}\\
\toprule
Variable Name & Description\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
Tract & Census tract FIPS code\\
NAME & Tract name/geographic identifier\\
TotHH & Total households in tract\\
TotPerson & Total persons in tract\\
Age18to34 & Population aged 18-34\\
Age35to49 & Population aged 35-49\\
Age50to64 & Population aged 50-64\\
Age65plus & Population aged 65 and older\\
AgeUnder18 & Population under age 18\\
Adult18plus & Population aged 18 and older\\
CompMOS & Composite measure of size used for PPS selection\\
nBGs & Number of block groups in tract\\*
\end{longtable}
\endgroup{}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{ll}
\caption{\label{tab:codebook-tables}Codebook for the Sample File (SAMPLE\_NEYMAN.csv)}\\
\toprule
Variable Name & Description\\
\midrule
\endfirsthead
\caption[]{Codebook for the Sample File (SAMPLE\_NEYMAN.csv) \textit{(continued)}}\\
\toprule
Variable Name & Description\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
BlockGroup & Selected block group FIPS code\\
TractFIPS & Parent tract FIPS code\\
TotHH & Total households in block group\\
TotPerson & Total persons in block group\\
Adult18plus & Population aged 18 and older in block group\\
Age18to34 & Population aged 18-34 in block group\\
Age35to49 & Population aged 35-49 in block group\\
Age50to64 & Population aged 50-64 in block group\\
Age65plus & Population aged 65+ in block group\\
CompMOS & Composite measure of size for the block group\\
pi\_tract & First-stage inclusion probability for the tract\\
pi\_bg\_given\_tract & Conditional second-stage inclusion probability for the block group\\
pi\_overall\_bg & Overall block-group selection probability\\
f\_person\_18to34 & Person sampling rate for age 18-34\\
f\_person\_35to49 & Person sampling rate for age 35-49\\
f\_person\_50to64 & Person sampling rate for age 50-64\\
f\_person\_65plus & Person sampling rate for age 65+\\
listed\_18to34 & Expected number of listed persons selected in age 18-34\\
listed\_35to49 & Expected number of listed persons selected in age 35-49\\
listed\_50to64 & Expected number of listed persons selected in age 50-64\\
listed\_65plus & Expected number of listed persons selected in age 65+\\
total\_listed & Expected total persons selected before nonresponse\\
expected\_resp\_18to34 & Expected completed interviews in age 18-34 from fractional rates\\
expected\_resp\_35to49 & Expected completed interviews in age 35-49 from fractional rates\\
expected\_resp\_50to64 & Expected completed interviews in age 50-64 from fractional rates\\
expected\_resp\_65plus & Expected completed interviews in age 65+ from fractional rates\\
expected\_total\_resp & Expected total completed interviews from fractional rates\\
base\_wt\_18to34 & Base weight for persons aged 18-34\\
base\_wt\_35to49 & Base weight for persons aged 35-49\\
base\_wt\_50to64 & Base weight for persons aged 50-64\\
base\_wt\_65plus & Base weight for persons aged 65+\\
select\_n\_18to34 & Operational integer persons to select in age 18-34\\
select\_n\_35to49 & Operational integer persons to select in age 35-49\\
select\_n\_50to64 & Operational integer persons to select in age 50-64\\
select\_n\_65plus & Operational integer persons to select in age 65+\\
expected\_comp\_from\_select\_18to34 & Expected completed interviews from operational 18-34 selections\\
expected\_comp\_from\_select\_35to49 & Expected completed interviews from operational 35-49 selections\\
expected\_comp\_from\_select\_50to64 & Expected completed interviews from operational 50-64 selections\\
expected\_comp\_from\_select\_65plus & Expected completed interviews from operational 65+ selections\\
total\_selected & Total operational persons selected in the block group\\
expected\_total\_comp\_from\_select & Expected total completed interviews from operational integer selections\\*
\end{longtable}
\endgroup{}

\subsection{Listing of Sample PSUs and SSUs with Selection Probabilities
and Sampling
Rates}\label{listing-of-sample-psus-and-ssus-with-selection-probabilities-and-sampling-rates}

\begingroup\fontsize{7}{9}\selectfont

\begin{longtable}[t]{llrrrrrrrrrrrrrrrrrrr}
\caption{\label{tab:appendix-sample-listing}Selected Tracts and Block Groups with Selection Probabilities and Person Sampling Rates}\\
\toprule
Tract & BlockGroup & TotHH & TotPerson & Adult18plus & Age18to34 & Age35to49 & Age50to64 & Age65plus & CompMOS & pi\_tract & pi\_bg\_given\_tract & pi\_overall\_bg & f\_person\_18to34 & f\_person\_35to49 & f\_person\_50to64 & f\_person\_65plus & select\_n\_18to34 & select\_n\_35to49 & select\_n\_50to64 & select\_n\_65plus\\
\midrule
\endfirsthead
\caption[]{Selected Tracts and Block Groups with Selection Probabilities and Person Sampling Rates \textit{(continued)}}\\
\toprule
Tract & BlockGroup & TotHH & TotPerson & Adult18plus & Age18to34 & Age35to49 & Age50to64 & Age65plus & CompMOS & pi\_tract & pi\_bg\_given\_tract & pi\_overall\_bg & f\_person\_18to34 & f\_person\_35to49 & f\_person\_50to64 & f\_person\_65plus & select\_n\_18to34 & select\_n\_35to49 & select\_n\_50to64 & select\_n\_65plus\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
26163500200 & 261635002002 & 764 & 2180 & 1480 & 538 & 394 & 347 & 201 & 6.6688 & 0.1746 & 0.7090 & 0.1238 & 0.0358 & 0.0396 & 0.0343 & 0.0354 & 20 & 15 & 12 & 7\\
26163500900 & 261635009002 & 879 & 2049 & 1419 & 513 & 390 & 345 & 171 & 6.3985 & 0.2151 & 0.5523 & 0.1188 & 0.0373 & 0.0413 & 0.0357 & 0.0369 & 20 & 16 & 12 & 6\\
26163501400 & 261635014002 & 412 & 990 & 709 & 238 & 185 & 189 & 97 & 3.1888 & 0.2241 & 0.2642 & 0.0592 & 0.0748 & 0.0828 & 0.0717 & 0.0740 & 19 & 15 & 13 & 7\\
26163502000 & 261635020001 & 766 & 1858 & 1289 & 437 & 357 & 346 & 149 & 5.8080 & 0.1078 & 1.0000 & 0.1078 & 0.0411 & 0.0455 & 0.0394 & 0.0407 & 19 & 16 & 13 & 6\\
26163503400 & 261635034001 & 494 & 886 & 673 & 203 & 178 & 190 & 102 & 3.0257 & 0.0562 & 1.0000 & 0.0562 & 0.0788 & 0.0873 & 0.0756 & 0.0780 & 17 & 15 & 14 & 8\\
26163505100 & 261635051003 & 518 & 1325 & 1018 & 310 & 220 & 290 & 198 & 4.5508 & 0.1871 & 0.4516 & 0.0845 & 0.0524 & 0.0580 & 0.0503 & 0.0519 & 17 & 13 & 14 & 10\\
26163506100 & 261635061001 & 744 & 1875 & 1379 & 507 & 319 & 336 & 217 & 6.1871 & 0.1149 & 1.0000 & 0.1149 & 0.0385 & 0.0427 & 0.0370 & 0.0382 & 21 & 13 & 12 & 8\\
26163506900 & 261635069003 & 418 & 905 & 674 & 213 & 177 & 145 & 139 & 3.0362 & 0.2130 & 0.2647 & 0.0564 & 0.0785 & 0.0870 & 0.0753 & 0.0778 & 18 & 15 & 11 & 10\\
26163508000 & 261635080001 & 626 & 1098 & 835 & 270 & 210 & 270 & 85 & 3.7444 & 0.0695 & 1.0000 & 0.0695 & 0.0637 & 0.0706 & 0.0611 & 0.0631 & 18 & 15 & 16 & 5\\
26163511400 & 261635114001 & 678 & 1026 & 832 & 261 & 176 & 206 & 189 & 3.7220 & 0.1388 & 0.4978 & 0.0691 & 0.0641 & 0.0710 & 0.0614 & 0.0634 & 18 & 12 & 12 & 12\\
26163513900 & 261635139001 & 453 & 765 & 612 & 169 & 116 & 182 & 145 & 2.7256 & 0.0966 & 0.5239 & 0.0506 & 0.0875 & 0.0969 & 0.0839 & 0.0866 & 16 & 11 & 15 & 12\\
26163515700 & 261635157001 & 1429 & 1766 & 1663 & 551 & 278 & 358 & 476 & 7.4097 & 0.3630 & 0.3790 & 0.1376 & 0.0322 & 0.0357 & 0.0309 & 0.0319 & 19 & 10 & 11 & 15\\
26163516700 & 261635167003 & 787 & 1254 & 1090 & 269 & 226 & 298 & 297 & 4.8667 & 0.2155 & 0.4192 & 0.0904 & 0.0490 & 0.0543 & 0.0470 & 0.0485 & 14 & 12 & 14 & 14\\
26163517500 & 261635175002 & 1205 & 1392 & 1282 & 456 & 178 & 324 & 324 & 5.6879 & 0.2080 & 0.5076 & 0.1056 & 0.0419 & 0.0464 & 0.0402 & 0.0415 & 20 & 8 & 13 & 13\\
26163520300 & 261635203001 & 575 & 652 & 584 & 291 & 86 & 115 & 92 & 2.6017 & 0.2078 & 0.2325 & 0.0483 & 0.0917 & 0.1015 & 0.0879 & 0.0908 & 28 & 9 & 10 & 8\\
26163521800 & 261635218001 & 901 & 1466 & 1179 & 282 & 207 & 249 & 441 & 5.2543 & 0.0976 & 1.0000 & 0.0976 & 0.0454 & 0.0503 & 0.0435 & 0.0449 & 13 & 10 & 11 & 19\\
26163523300 & 261635233003 & 330 & 934 & 646 & 277 & 165 & 136 & 68 & 2.9112 & 0.1699 & 0.3181 & 0.0540 & 0.0819 & 0.0907 & 0.0786 & 0.0811 & 24 & 15 & 10 & 5\\
26163524200 & 261635242001 & 547 & 1593 & 1070 & 430 & 347 & 182 & 111 & 4.8650 & 0.2429 & 0.3719 & 0.0903 & 0.0490 & 0.0543 & 0.0470 & 0.0485 & 22 & 19 & 8 & 5\\
26163525700 & 261635257004 & 433 & 1368 & 889 & 298 & 312 & 191 & 88 & 4.0463 & 0.2451 & 0.3065 & 0.0751 & 0.0589 & 0.0653 & 0.0565 & 0.0584 & 18 & 20 & 11 & 5\\
26163526400 & 261635264001 & 248 & 742 & 506 & 201 & 144 & 97 & 64 & 2.2886 & 0.0808 & 0.5259 & 0.0425 & 0.1042 & 0.1154 & 0.0999 & 0.1032 & 22 & 16 & 9 & 6\\
26163530800 & 261635308002 & 466 & 603 & 444 & 160 & 90 & 112 & 82 & 1.9848 & 0.0906 & 0.4068 & 0.0369 & 0.1201 & 0.1331 & 0.1152 & 0.1190 & 20 & 12 & 13 & 9\\
26163531800 & 261635318001 & 465 & 779 & 576 & 191 & 139 & 153 & 93 & 2.5847 & 0.0937 & 0.5124 & 0.0480 & 0.0923 & 0.1022 & 0.0885 & 0.0914 & 18 & 14 & 13 & 8\\
26163533600 & 261635336002 & 577 & 816 & 597 & 172 & 169 & 156 & 100 & 2.6911 & 0.0864 & 0.5781 & 0.0500 & 0.0886 & 0.0982 & 0.0850 & 0.0877 & 16 & 16 & 13 & 8\\
26163534700 & 261635347001 & 544 & 1104 & 764 & 237 & 192 & 180 & 155 & 3.4347 & 0.1843 & 0.3461 & 0.0638 & 0.0694 & 0.0769 & 0.0666 & 0.0687 & 17 & 15 & 12 & 10\\
26163535600 & 261635356001 & 299 & 659 & 531 & 133 & 114 & 152 & 132 & 2.3720 & 0.2404 & 0.1832 & 0.0440 & 0.1005 & 0.1114 & 0.0964 & 0.0995 & 14 & 13 & 14 & 13\\
26163536500 & 261635365002 & 644 & 1207 & 906 & 275 & 234 & 224 & 173 & 4.0747 & 0.1332 & 0.5678 & 0.0757 & 0.0585 & 0.0648 & 0.0561 & 0.0579 & 17 & 15 & 12 & 10\\
26163537200 & 261635372001 & 350 & 583 & 450 & 122 & 131 & 126 & 71 & 2.0289 & 0.0377 & 1.0000 & 0.0377 & 0.1175 & 0.1302 & 0.1127 & 0.1164 & 15 & 17 & 14 & 8\\
26163538200 & 261635382001 & 436 & 1105 & 905 & 193 & 222 & 222 & 268 & 4.0608 & 0.1349 & 0.5590 & 0.0754 & 0.0587 & 0.0651 & 0.0563 & 0.0581 & 12 & 14 & 12 & 15\\
26163538600 & 261635386003 & 457 & 1111 & 882 & 248 & 187 & 251 & 196 & 3.9401 & 0.3010 & 0.2430 & 0.0732 & 0.0605 & 0.0670 & 0.0580 & 0.0599 & 16 & 12 & 14 & 11\\
26163539200 & 261635392001 & 1142 & 2152 & 1745 & 396 & 409 & 480 & 460 & 7.8139 & 0.3245 & 0.4470 & 0.1451 & 0.0305 & 0.0338 & 0.0293 & 0.0302 & 13 & 14 & 14 & 13\\
26163539600 & 261635396002 & 728 & 1829 & 1389 & 391 & 340 & 323 & 335 & 6.2387 & 0.2030 & 0.5707 & 0.1158 & 0.0382 & 0.0423 & 0.0367 & 0.0378 & 16 & 14 & 12 & 12\\
26163540400 & 261635404002 & 642 & 1232 & 962 & 258 & 215 & 286 & 203 & 4.3010 & 0.1684 & 0.4742 & 0.0799 & 0.0554 & 0.0614 & 0.0532 & 0.0549 & 15 & 13 & 15 & 11\\
26163540900 & 261635409001 & 452 & 993 & 743 & 212 & 164 & 186 & 181 & 3.3262 & 0.2197 & 0.2811 & 0.0618 & 0.0717 & 0.0794 & 0.0688 & 0.0710 & 16 & 13 & 13 & 12\\
26163541500 & 261635415001 & 814 & 1682 & 1352 & 373 & 289 & 378 & 312 & 6.0416 & 0.2405 & 0.4665 & 0.1122 & 0.0395 & 0.0437 & 0.0379 & 0.0391 & 15 & 13 & 14 & 12\\
26163542300 & 261635423001 & 367 & 858 & 667 & 217 & 161 & 149 & 140 & 2.9968 & 0.1452 & 0.3832 & 0.0556 & 0.0796 & 0.0882 & 0.0763 & 0.0788 & 18 & 14 & 11 & 11\\
26163543100 & 261635431002 & 420 & 1107 & 878 & 206 & 178 & 218 & 276 & 3.9206 & 0.1591 & 0.4574 & 0.0728 & 0.0608 & 0.0674 & 0.0583 & 0.0602 & 13 & 12 & 12 & 16\\
26163544000 & 261635440001 & 1250 & 2534 & 1985 & 694 & 473 & 568 & 250 & 8.9001 & 0.1652 & 1.0000 & 0.1652 & 0.0268 & 0.0297 & 0.0257 & 0.0265 & 20 & 14 & 14 & 6\\
26163545500 & 261635455001 & 440 & 1245 & 835 & 308 & 231 & 196 & 100 & 3.7672 & 0.2171 & 0.3222 & 0.0699 & 0.0633 & 0.0701 & 0.0607 & 0.0627 & 20 & 16 & 12 & 6\\
26163545900 & 261635459001 & 826 & 1861 & 1282 & 494 & 348 & 309 & 131 & 5.7802 & 0.2118 & 0.5067 & 0.1073 & 0.0413 & 0.0457 & 0.0396 & 0.0409 & 21 & 16 & 12 & 5\\
26163546700 & 261635467002 & 559 & 1091 & 823 & 285 & 202 & 210 & 126 & 3.6965 & 0.1741 & 0.3943 & 0.0686 & 0.0645 & 0.0715 & 0.0619 & 0.0639 & 19 & 14 & 13 & 8\\*
\end{longtable}
\endgroup{}

\subsection{Online Sources Used}\label{online-sources-used}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{lll}
\caption{\label{tab:source-links}Online Sources Referenced for Data, Geography, and Project Context}\\
\toprule
Source & Role & URL\\
\midrule
\endfirsthead
\caption[]{Online Sources Referenced for Data, Geography, and Project Context \textit{(continued)}}\\
\toprule
Source & Role & URL\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
Census API data portal & Documented the Decennial Census API endpoints and dataset structure used to obtain Detroit tract and block-group counts. & https://api.census.gov/data.html\\
Census API key signup page & Documented the reproducible Census API access process for users who want to rebuild the source extracts. & https://api.census.gov/data/key\_signup.html\\
Detroit transportation insecurity report & Provided substantive background for the transportation insecurity focus of the survey design. & https://detroitsurvey.umich.edu/wp-content/uploads/2025/02/Transportation-Insecurity-in-the-Motor-City\_FINAL.pdf\\
Census geography glossary & Provided definitions for census tracts, block groups, and the standard census geographic hierarchy. & https://www.census.gov/programs-surveys/geography/about/glossary.html\\
Census reference maps page & Provided guidance on how Census reference maps identify boundaries and geographic labels. & https://www.census.gov/programs-surveys/geography/geographies/reference-maps.html\\
Census geographic hierarchy diagram & Provided a visual reference for how census geography nests from tract to block group and block. & https://www2.census.gov/geo/pdfs/reference/geodiagram.pdf\\*
\end{longtable}
\endgroup{}

\subsection{Disclosure of AI Use}\label{disclosure-of-ai-use}

GitHub Copilot using GPT-5.4 was used to review, revise, and package the
final version of this project. The assistance covered four tasks: (1)
checking the report and frame/sample documents against the project
instructions; (2) cleaning the Quarto and R Markdown source files so
they would render consistently; (3) updating the disclosure and
source-reference appendices; and (4) assembling the final deliverables
into a separate folder.

We take responsibility for all methodological decisions, formula
derivations, code review, data preparation, and final submission choices
in this work.

\textbf{Verbatim prompts used with GitHub Copilot (GPT-5.4):}

\begin{quote}
\emph{``Properly generate a .qmd file with all the codes written
properly and the report as per the instructions.''}
\end{quote}

\begin{quote}
\emph{``Go through all the links provided in the Project.pdf and
accurately generate the codes in the qmd file and in the report.''}
\end{quote}

\begin{quote}
\emph{``Please make sure to update these based on the AI model or
assistant that you used.''}
\end{quote}

\subsection{Output Files}\label{output-files}

\begin{table}[!h]
\centering
\caption{\label{tab:write-output-files}Output Files Written by the Script}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lr}
\toprule
File & Rows\\
\midrule
FRAME1\_NEYMAN.csv & 266\\
FRAME2\_NEYMAN.csv & 614\\
SAMPLE\_NEYMAN.csv & 40\\
\bottomrule
\end{tabular}}
\end{table}




\end{document}
